version: '3.9'

services:
  nestapp:
    container_name: nestapp
    image: amri/nestapp:1.0.0
    build: .
    ports:
      - 3000:3000
    environment:
      - DB_TYPE=postgresgg
      - PG_HOST=db 
      - PG_USER=postgres
      - PG_PASSWORD=root
      - PG_DB=test_db
      - PG_PORT=5432
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=test_db
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}